export const FETCH_TURNOVERS_REQUEST = "FETCH_TURNOVERS_REQUEST";
export const FETCH_TURNOVERS_SUCCESS = "FETCH_TURNOVERS_SUCCESS";
export const FETCH_TURNOVERS_FAILED = "FETCH_TURNOVERS_FAILED";

export const ADD_APPLICANT_REQUEST = "ADD_APPLICANT_REQUEST";
export const ADD_APPLICANT_SUCCESS = "ADD_APPLICANT_SUCCESS";
export const ADD_APPLICANT_FAILED = "ADD_APPLICANT_FAILED";
