export const FETCH_EVENTS_REQUEST = "FETCH_EVENTS_REQUEST";
export const FETCH_EVENTS_SUCCESS = "FETCH_EVENTS_SUCCESS";
export const FETCH_EVENTS_FAILED = "FETCH_EVENTS_FAILED";

export const FETCH_EVENT_BY_ID_REQUEST = "FETCH_EVENT_BY_ID_REQUEST";
export const FETCH_EVENT_BY_ID_SUCCESS = "FETCH_EVENT_BY_ID_SUCCESS";
export const FETCH_EVENT_BY_ID_FAILED = "FETCH_EVENT_BY_ID_FAILED";

