export const FETCH_NEWS_REQUEST = "FETCH_NEWS_REQUEST";
export const FETCH_NEWS_SUCCESS = "FETCH_NEWS_SUCCESS";
export const FETCH_NEWS_FAILED = "FETCH_NEWS_FAILED";


export const FETCH_NEWS_BY_ID_REQUEST = "FETCH_NEWS_BY_ID_REQUEST";
export const FETCH_NEWS_BY_ID_SUCCESS = "FETCH_NEWS_BY_ID_SUCCESS";
export const FETCH_NEWS_BY_ID_FAILED = "FETCH_NEWS_BY_ID_FAILED";